apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecaster-stock
  labels:
    app: stock-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-service
      tier: backend
  template:
    metadata:
      labels:
        app: stock-service
        tier: backend
    spec:
      containers:
      - name: stock-service
        image: forecaster-stock
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_DB_ADDR
          value: java-guestbook-mongodb:27017
        - name: UI_API_ADDR
          value: forecaster-ui:80
          
